### ISSUE TITLE
General - Reintegrar logo en headers. 

### ISSUE THREAD

**Issue by J0rgePreciado** [aorimx/int-m#36]
Les recuerdo que el isotipo (símbolo) de Intermed tiene que estar siempre presente como parte del logo en la interface de cualquier aplicación. 
Lo removieron y hay que reintegrarlo. 
Incluso, como indicación general, si se requiere minimizar el uso de espacios es mas aceptable remover el texto "Intermed" del logo y usar solo el símbolo.

**Comment by AtidYarok** [comment]
Problema Resuelto , ya están los cambios incluidos en el Head y los modales también.
